# Chapter 1: Retrieiving Records
Make sure to follow `setup.ipynb` before you begin!

In [56]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("../sql.db")

## 1.1 Retrieving All Rows and Columns from a Table

**Problem:** You have a table and want to see all of the data in it.  
  
**Solution:** Use the special `*` character and issue a `SELECT` against the table

In [91]:
df = pd.read_sql_query("""
    SELECT * 
    FROM Emp;
""", conn)
df

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7369   SMITH      CLERK  7902.0  1980-12-17   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  1982-12-09  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  1981-11-17  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  1983-01-12  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  1981-12-03   950     NaN      30
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300     NaN      10

In [90]:
df = pd.read_sql_query("""
    SELECT * 
    FROM Dept;
""", conn)
df

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

## 1.2 Retrieiving a Subset of Rows from a Table

**Problem:** You have a table and want to see only rows that satisfy a specific condition.  

**Solution:** Use the WHERE clause to specify which rows to keep.

In [89]:
df = pd.read_sql_query("""
    SELECT * 
    FROM Emp
    WHERE deptno = 10;
""", conn)
df

   empno   ename        job     mgr    hiredate   sal  comm  deptno
0   7782   CLARK    MANAGER  7839.0  1981-06-09  2450  None      10
1   7839    KING  PRESIDENT     NaN  1981-11-17  5000  None      10
2   7934  MILLER      CLERK  7782.0  1982-01-23  1300  None      10

## 1.3 Finding Rows That Satisfy Multiple Conditions

**Problem:** You want to return rows that satisfy multiple conditions.  

**Solution:** Use the `WHERE` clause along with the `OR` and `AND` clauses.

In [88]:
df = pd.read_sql_query("""
    SELECT * 
    FROM Emp
    WHERE deptno = 10
        OR comm IS NOT NULL
        OR sal <= 2000 AND deptno = 20;
""", conn)
df

   empno   ename        job     mgr    hiredate   sal    comm  deptno
0   7369   SMITH      CLERK  7902.0  1980-12-17   800     NaN      20
1   7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600   300.0      30
2   7521    WARD   SALESMAN  7698.0  1981-02-22  1250   500.0      30
3   7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250  1400.0      30
4   7782   CLARK    MANAGER  7839.0  1981-06-09  2450     NaN      10
5   7839    KING  PRESIDENT     NaN  1981-11-17  5000     NaN      10
6   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500     0.0      30
7   7876   ADAMS      CLERK  7788.0  1983-01-12  1100     NaN      20
8   7934  MILLER      CLERK  7782.0  1982-01-23  1300     NaN      10

## 1.4 Retrieving a Subset of Columns from a table

**Problem:** You have a table and want to see values for specific columns rather than for all the columns.  

**Solution:** Specify the columns you're interested in instead of using `*`.

In [87]:
df = pd.read_sql_query("""
    SELECT ename, deptno, sal 
    FROM EMP;
""", conn)
df

     ename  deptno   sal
0    SMITH      20   800
1    ALLEN      30  1600
2     WARD      30  1250
3    JONES      20  2975
4   MARTIN      30  1250
5    BLAKE      30  2850
6    CLARK      10  2450
7    SCOTT      20  3000
8     KING      10  5000
9   TURNER      30  1500
10   ADAMS      20  1100
11   JAMES      30   950
12    FORD      20  3000
13  MILLER      10  1300

## 1.5 Providing Meaningful Names for Columns

**Problem:** You would like to change the names of the columns that are returned by the query so they are more readable and understandable. 

**Solution:** To change the names of your query results, use the `AS` keyword in for form of *original_name AS new_name*.

In [86]:
df = pd.read_sql_query("""
    SELECT sal AS salary, comm AS commission 
    FROM Emp;
""", conn)

df

    salary  commission
0      800         NaN
1     1600       300.0
2     1250       500.0
3     2975         NaN
4     1250      1400.0
5     2850         NaN
6     2450         NaN
7     3000         NaN
8     5000         NaN
9     1500         0.0
10    1100         NaN
11     950         NaN
12    3000         NaN
13    1300         NaN

## 1.6 Referencing an Aliased Column in the WHERE Clause

**Problem:** You have used aliases to provide more meaningful column names for your result set and would like to exclude some of the rows using the `WHERE` clause.  

**Solution:** By wrapping your query as an inline view, you can reference the aliased columns.

**Notes:** The `WHERE` clause evaulates before the `SELECT` clause if you don't use an inline view, hence the need for one in order to reference the aliased.

In [85]:
df = pd.read_sql_query("""
SELECT * 
FROM (
    SELECT sal AS salary, comm AS commission FROM Emp
) x
WHERE salary < 5000;
""", conn)
df

    salary  commission
0      800         NaN
1     1600       300.0
2     1250       500.0
3     2975         NaN
4     1250      1400.0
5     2850         NaN
6     2450         NaN
7     3000         NaN
8     1500         0.0
9     1100         NaN
10     950         NaN
11    3000         NaN
12    1300         NaN

## 1.7 Concatenating Column Values

**Problem:** You want to return values in multiple columns as one column.

**Solution:** Use the built in concat function or concatenation operator per DBMS

In [64]:
df = pd.read_sql_query("""
    SELECT CONCAT(ename, ' WORKS AS A ', job) AS msg 
    FROM Emp 
    WHERE deptno=10;
""", conn)
df

                         msg
0   CLARK WORKS AS A MANAGER
1  KING WORKS AS A PRESIDENT
2    MILLER WORKS AS A CLERK

## 1.8 Using Conditional Logic in a SELECT Statement

**Problem:** You want to perform IF-ELSE operations on values in your `SELECT` statement.

**Solution:** Use the `CASE` expression to perform conditional logic directly in your `SELECT` statement

**Notes:** CASE allows you to perform conditional logic on values returned by a query

In [65]:
df = pd.read_sql_query("""
    SELECT ename, sal,
        CASE WHEN sal <= 2000 THEN 'UNDERPAID'
            WHEN sal >= 4000 THEN 'OVERPAID'
            else 'OK'
        END AS status
    FROM Emp;
""", conn)
df

     ename   sal     status
0    SMITH   800  UNDERPAID
1    ALLEN  1600  UNDERPAID
2     WARD  1250  UNDERPAID
3    JONES  2975         OK
4   MARTIN  1250  UNDERPAID
5    BLAKE  2850         OK
6    CLARK  2450         OK
7    SCOTT  3000         OK
8     KING  5000   OVERPAID
9   TURNER  1500  UNDERPAID
10   ADAMS  1100  UNDERPAID
11   JAMES   950  UNDERPAID
12    FORD  3000         OK
13  MILLER  1300  UNDERPAID

## 1.9 Limiting the Number of Rows Returned

**Problem:** You want to limit the number of rows returned in your query, orderless.

**Solution:** Use the LIMIT function, DBMS specific

In [84]:
df = pd.read_sql_query("""
    SELECT * 
    FROM Emp LIMIT 5;
""", conn)
df

   empno   ename       job   mgr    hiredate   sal    comm  deptno
0   7369   SMITH     CLERK  7902  1980-12-17   800     NaN      20
1   7499   ALLEN  SALESMAN  7698  1981-02-20  1600   300.0      30
2   7521    WARD  SALESMAN  7698  1981-02-22  1250   500.0      30
3   7566   JONES   MANAGER  7839  1981-04-02  2975     NaN      20
4   7654  MARTIN  SALESMAN  7698  1981-09-28  1250  1400.0      30

## 1.10 Returning n Random Records from a Table

**Problem:** You want to return a specific number of random records from a table

**Solution:** Use the DBMS-specific Random function in an `ORDER BY` clause to sort rows randomly.

In [81]:
df = pd.read_sql_query("""
    SELECT ename, job 
    FROM Emp 
    ORDER BY RANDOM() LIMIT 5;
""", conn)
df

   ename       job
0   FORD   ANALYST
1  JAMES     CLERK
2  ADAMS     CLERK
3  CLARK   MANAGER
4   WARD  SALESMAN

## 1.11 Finding Null Values

**Problem:** You want to find all rows that are null for a particular column.

**Solution:** Use `IS NULL`

**Notes:** NULL is never equal or not equal to anything so comparisons fail. Only way to tell is using `IS NULL` or `IS NOT NULL`.

In [83]:
df = pd.read_sql_query("""
    SELECT * 
    FROM Emp 
    WHERE comm IS NULL;
""", conn)
df

   empno   ename        job     mgr    hiredate   sal  comm  deptno
0   7369   SMITH      CLERK  7902.0  1980-12-17   800  None      20
1   7566   JONES    MANAGER  7839.0  1981-04-02  2975  None      20
2   7698   BLAKE    MANAGER  7839.0  1981-05-01  2850  None      30
3   7782   CLARK    MANAGER  7839.0  1981-06-09  2450  None      10
4   7788   SCOTT    ANALYST  7566.0  1982-12-09  3000  None      20
5   7839    KING  PRESIDENT     NaN  1981-11-17  5000  None      10
6   7876   ADAMS      CLERK  7788.0  1983-01-12  1100  None      20
7   7900   JAMES      CLERK  7698.0  1981-12-03   950  None      30
8   7902    FORD    ANALYST  7566.0  1981-12-03  3000  None      20
9   7934  MILLER      CLERK  7782.0  1982-01-23  1300  None      10

## 1.12 Transforming Nulls into Real Values

**Problem:** You have rows that contain nulls and would like to return non-null values in place of those nulls.

**Solution:** Use the function `COALESCE` to substitute real values for nulls.

**Notes:** The `COALESCE` function takes one or more values as arguments and returns the first non-null value in the list. `CASE` can be used to handle nulls as well.

In [82]:
df = pd.read_sql_query("""
    SELECT COALESCE(comm, 0) 
    FROM Emp;
""", conn)
df

    COALESCE(comm, 0)
0                   0
1                 300
2                 500
3                   0
4                1400
5                   0
6                   0
7                   0
8                   0
9                   0
10                  0
11                  0
12                  0
13                  0

In [80]:
df = pd.read_sql_query("""
    SELECT CASE
        WHEN comm IS NOT NULL then comm
        ELSE 0
        END AS comm
    FROM Emp;
""", conn)
df

    comm
0      0
1    300
2    500
3      0
4   1400
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0

## 1.13 Searching for Patterns

**Problem:** You want to return rows that match a particular substring or pattern.

**Solution:** Use the `LIKE` operator in conjunction with the SQL wildcard operator `%`

**Notes:** The `%` operator matches any sequence of characters. The `_` operator matches a single character.

In [93]:
df = pd.read_sql_query("""
    SELECT ename, job
    FROM emp
    WHERE deptno in (10, 20)
    AND (ename LIKE '%I%' OR job LIKE '%ER');
""", conn)
df

    ename        job
0   SMITH      CLERK
1   JONES    MANAGER
2   CLARK    MANAGER
3    KING  PRESIDENT
4  MILLER      CLERK